/* ——— PORTAL LINKS ——— */
const allLinks = [
  /* Academics */
  { name: 'NTULearn', desc: 'Course materials, assignments, announcements', cat: 'Academics', url: 'https://ntulearn.ntu.edu.sg/ultra/institution-page' },
  { name: 'Degree Audit', desc: 'View grades and track AU progress', cat: 'Academics', url: 'https://wish.wis.ntu.edu.sg/pls/webexe/ldap_login.login?w_url=https://wish.wis.ntu.edu.sg/pls/webexe/dars_result_ro.main_display' },
  { name: 'STARS', desc: 'Register for courses and plan timetable', cat: 'Academics', url: 'https://wish.wis.ntu.edu.sg/pls/webexe/ldap_login.login?w_url=https://wish.wis.ntu.edu.sg/pls/webexe/aus_stars_planner.main' },
  { name: 'Exam Seating', desc: 'Exam venue and seat number', cat: 'Academics', url: 'https://sso.wis.ntu.edu.sg/webexe88/owa/sso_login1.asp?t=1&p2=https://wis.ntu.edu.sg/webexe/owa/oes_main.main&extra=&pg=' },
  { name: 'Exam Timetable', desc: 'Exam schedule for current semester', cat: 'Academics', url: 'https://wis.ntu.edu.sg/webexe/owa/exam_timetable_und.main' },
  { name: 'Transcript', desc: 'View grades history', cat: 'Academics', url: 'https://wis.ntu.edu.sg/webexe/owa/request_transcript_und.LoginN?pType=SH' },
  { name: 'S/U Option', desc: 'Satisfactory/Unsatisfactory grading election', cat: 'Academics', url: 'https://sso.wis.ntu.edu.sg/webexe88/owa/sso_login1.asp?t=1&p2=https://wis.ntu.edu.sg/pls/webexe/aus_su_opt.display&extra=&pg=' },
  { name: 'Class Schedule', desc: 'Browse available classes for any module', cat: 'Academics', url: 'https://wish.wis.ntu.edu.sg/webexe/owa/aus_schedule.main' },
  { name: 'LOA Form', desc: 'Leave of absence application form', cat: 'Academics', url: 'https://entuedu.sharepoint.com/sites/Student/dept/sasd/oas/Shared%20Documents/Forms/display.aspx?id=%2Fsites%2FStudent%2Fdept%2Fsasd%2Foas%2FShared%20Documents%2FCandidature%2FShort%20Leave%20Application%20Form0324%2Epdf' },
  { name: 'Academic Calendar', desc: 'Semester dates, recess weeks, exam periods and public holidays', cat: 'Academics', url: 'https://www.ntu.edu.sg/admissions/matriculation/academic-calendars' },
  { name: 'Library Catalogue', desc: 'Search NTU library holdings — books, journals, databases and e-resources', cat: 'Academics', url: 'https://libguides.ntu.edu.sg/OneSearch' },
  { name: 'MOOC Transfer', desc: 'Credit transfer portal for approved online MOOCs. Submit completed certificates for AU recognition.', cat: 'Academics', url: 'https://sso.wis.ntu.edu.sg/webexe88/owa/sso_login1.asp?t=&p2=https://venus2.wis.ntu.edu.sg/MOOC/Student/Login.aspx&extra=&pg=' },
  { name: 'MOOC Guide', desc: "Approved MOOC platforms and eligibility for AU credit under NTU's recognition programme", cat: 'Academics', url: 'https://www.ntu.edu.sg/admissions/matriculation/mooc' },
  /* Career */
  { name: 'CareerAxis', desc: 'Internships, jobs and career events', cat: 'Career', url: 'https://careeraxis.ntu.edu.sg/students' },
  { name: 'Work Study Scheme', desc: 'Paid on-campus student opportunities that fit around your academic schedule', cat: 'Career', url: 'https://entuedu.sharepoint.com/sites/Student/dept/sasd/sao/SitePages/WSS/WSS.aspx' },
  /* Exchange */
  { name: 'Exchange Portal', desc: 'Semester exchanges and global programmes at partner universities worldwide', cat: 'Exchange', url: 'https://gem.ntu.edu.sg/' },
  { name: 'Course Matching', desc: 'Match overseas courses to NTU equivalents for credit transfer approval', cat: 'Exchange', url: 'https://sso.wis.ntu.edu.sg/webexe88/owa/sso_login1.asp?t=1&p2=https://wis.ntu.edu.sg/pls/lms/instep_past_subj_matching.show_rec_INSTEP' },
  /* Facilities */
  { name: 'Library Booking', desc: "Study rooms and library spaces across NTU's library network", cat: 'Facilities', url: 'https://libcalendar.ntu.edu.sg/' },
  { name: 'Facilities Booking', desc: 'Sports courts, function rooms and multi-purpose halls for club or personal use', cat: 'Facilities', url: 'https://ntu.facilitiesbooking.com/' },
  { name: 'Sports & Rec Centre', desc: 'Book facilities at the Sports & Recreation Centre — gym, pools, courts and fitness classes', cat: 'Facilities', url: 'https://www.ntu.edu.sg/life-at-ntu/recreational-spaces-facilities/sports-recreation-centre' },
  /* Finance */
  { name: 'Financial Aid', desc: 'Scholarships, bursaries, tuition grants and financial assistance for undergraduates', cat: 'Finance', url: 'https://www.ntu.edu.sg/admissions/undergraduate/financial-matters/financial-aid' },
  /* Housing */
  { name: 'Hall Portal', desc: 'Apply for on-campus housing, manage your hall room and submit maintenance requests', cat: 'Housing', url: 'https://ntusg.starrezhousing.com/StarRezStudentPortal' },
  /* Community */
  { name: 'NTU ConfessIt', desc: 'Anonymous confessions from the NTU student body — the unfiltered pulse of campus life', cat: 'Community', url: 'https://t.me/ntuconfessit' },
  { name: 'NTU Marketplace', desc: 'Student-to-student trading for textbooks, electronics, furniture and campus essentials', cat: 'Community', url: 'https://t.me/ntumarketplace' },
  { name: 'InUniSell', desc: 'NTU student marketplace website — buy and sell textbooks, electronics and campus items', cat: 'Community', url: 'https://inunisell.ntuscds.com/' },
  { name: 'NTU Atlas Community', desc: 'Suggest new links, report broken ones and connect with fellow students', cat: 'Community', url: 'https://t.me/ntulinksss' },
  { name: 'Clubs & Societies Directory', desc: 'Official NTU directory of all recognised student clubs and societies', cat: 'Community', url: 'https://www.ntu.edu.sg/life-at-ntu/student-life/student-activities-and-engagement/clubs-groups-societies' },
  /* Campus Life */
  { name: 'Campus Shuttle (Omnibus)', desc: 'NTU campus bus app guide — routes, timings and how to use the Omnibus mobile app', cat: 'Campus Life', url: 'https://ebook.ntu.edu.sg/ntu-omnibus-app-user-guide.html' },
  { name: 'Campus Map', desc: 'Interactive NTU campus map — find buildings, bus stops, canteens and facilities', cat: 'Campus Life', url: 'https://maps.ntu.edu.sg/' },
  { name: 'Food & Beverage', desc: 'NTU canteen locations, operating hours and food options across the campus', cat: 'Campus Life', url: 'https://www.ntu.edu.sg/life-at-ntu/leisure-and-dining/general-directory' },
  { name: 'Student Health Centre', desc: 'Book GP consultations, vaccinations and health screenings at the on-campus clinic', cat: 'Campus Life', url: 'https://www.ntu.edu.sg/life-at-ntu/health-and-safety/services/health-care' },
  { name: 'Counselling Services', desc: 'Free and confidential counselling and psychological support for all NTU students', cat: 'Campus Life', url: 'https://www.ntu.edu.sg/life-at-ntu/student-life/campus-life-and-wellbeing/ntu-wellbeing/student-well-being/Counselling-and-Psychological-Services' },
  /* IT & Tech */
  { name: 'NTU VPN', desc: 'Access NTU intranet resources off-campus using GlobalProtect VPN', cat: 'IT & Tech', url: 'https://vpngate.ntu.edu.sg/global-protect/getsoftwarepage.esp' },
  { name: 'eduroam Setup', desc: 'Connect to eduroam Wi-Fi on campus and at partner institutions worldwide', cat: 'IT & Tech', url: 'https://www.ntu.edu.sg/life-at-ntu/internet-account-and-policy/how-to-login-to-the-ntu-wireless-network' },
  { name: 'IT Service Desk', desc: 'Report IT issues, request software licences and get help with NTU tech services', cat: 'IT & Tech', url: 'https://entuedu.sharepoint.com/sites/Student/dept/imsc/SitePages/Home.aspx' },
  /* Student Services */
  { name: 'One Stop @ SAC', desc: 'Counter for academic records, letters, graduation matters and general student admin', cat: 'Student Services', url: 'https://www.ntu.edu.sg/life-at-ntu/student-life/student-services/onestop' },
  { name: 'Student Life Hub', desc: 'NTU student life — clubs, wellbeing, inclusion, community engagement and student support services', cat: 'Student Services', url: 'https://www.ntu.edu.sg/life-at-ntu/student-life' },
  { name: 'Global Education Office', desc: 'Support and resources for international students, exchanges and global education programmes', cat: 'Student Services', url: 'https://www.ntu.edu.sg/education/student-exchanges' },
  { name: 'Graduation', desc: 'Graduation eligibility checks, ceremony registration and collection of certificates', cat: 'Student Services', url: 'https://www.ntu.edu.sg/education/academic-services/graduation-matters' },
];

/* ——— CLUBS DATA ——— */
/* NOTE: instagram: handle only (no @, no URL) — null if unverified */
const allClubs = [

  /* ── Sports ── */
  { name: 'Badminton Club', type: 'Sports', desc: 'Competitive and recreational badminton for all levels, with inter-varsity IVP training and representation.', instagram: 'ntubadminton' },
  { name: 'Basketball Club', type: 'Sports', desc: "Men's and women's varsity basketball teams competing in IVP leagues and friendly tournaments.", instagram: 'ntubball' },
  { name: 'Football Club', type: 'Sports', desc: "NTU's flagship football club, fielding men's and women's teams in the IVP league.", instagram: 'ntufootball' },
  { name: 'Swimming & Water Polo', type: 'Sports', desc: 'Competitive swimming and water polo, training in the NTU Olympic-size pool with IVP representation.', instagram: 'ntu_swim_polo' },
  { name: 'Tennis Club', type: 'Sports', desc: 'Tennis training and inter-varsity competition for beginners through to advanced players.', instagram: 'ntutennisclub' },
  { name: 'Volleyball Club', type: 'Sports', desc: "Men's and women's volleyball teams with regular training and IVP fixtures.", instagram: 'ntuvb' },
  { name: 'Table Tennis Club', type: 'Sports', desc: 'Casual and competitive table tennis for all levels, with IVP league representation.', instagram: 'ntu.tabletennis' },
  { name: 'Floorball Club', type: 'Sports', desc: 'Recreational and competitive floorball with training sessions and inter-varsity participation.', instagram: 'nturecrefloorball' },
  { name: 'Archery Club', type: 'Sports', desc: 'Recurve, compound and barebow archery for beginners and competitive archers on campus.', instagram: 'ntuarchery' },
  { name: 'Bowling Club', type: 'Sports', desc: 'Recreational and competitive ten-pin bowling, with training at nearby alleys and varsity competition.', instagram: 'ntubowlers' },
  { name: 'Aces Cheerleading', type: 'Sports', desc: 'NTU\'s cheerleading squad performing stunts, pyramids and routines at campus events and competitions.', instagram: 'ntuaces' },
  { name: 'Fencing Club', type: 'Sports', desc: 'Foil, épée and sabre fencing for all experience levels, with IVP competitive representation.', instagram: 'ntufencingclub' },
  { name: 'Golf Club', type: 'Sports', desc: 'Golf training and inter-varsity competition for students of all handicap levels.', instagram: 'ntugolfclub' },
  { name: 'Ice Skating Club', type: 'Sports', desc: 'Recreational ice skating sessions and beginner classes at rinks around Singapore.', instagram: 'ntuonice' },
  { name: 'Inline Skating Club', type: 'Sports', desc: 'Recreational and freestyle inline skating sessions and skill workshops.', instagram: 'ntu_inlineskateclub' },
  { name: 'Lifesaving Club', type: 'Sports', desc: 'Water safety, lifesaving skills and competitive lifesaving sport, affiliated with Singapore Lifesaving.', instagram: 'ntulifesaving' },
  { name: "Runners' Club", type: 'Sports', desc: 'Regular group runs, long-distance training and participation in local road races and fun runs.', instagram: 'nturunnersclub' },
  { name: 'Sailing Club', type: 'Sports', desc: 'Dinghy and keelboat sailing at Changi Sailing Club, open to complete beginners.', instagram: 'ntusailing' },
  { name: 'Scuba Diving Club', type: 'Sports', desc: 'PADI-certified scuba diving training and dive trips around Singapore and the region.', instagram: 'ntuscubaofficial' },
  { name: 'Snooker & Pool Club', type: 'Sports', desc: 'Casual and competitive billiards — snooker, 8-ball and 9-ball — at the on-campus pool hall.', instagram: 'ntu_spc' },
  { name: 'Sport Climbing Club', type: 'Sports', desc: 'Bouldering, lead and top-rope climbing at the NTU wall and external gyms, for all abilities.', instagram: 'ntu_scc' },
  { name: 'Wakeboarding Club', type: 'Sports', desc: 'Wakeboarding and waterskiing at cable parks — beginner packages and progression programmes available.', instagram: 'ntuwakeboardingclub' },
  { name: 'Windsurfing Club', type: 'Sports', desc: 'Windsurfing training at East Coast Park, catering to beginners and experienced sailors.', instagram: 'ntuwindsurf' },
  { name: 'Aikido Club', type: 'Sports', desc: 'Traditional Japanese martial art focusing on joint locks and throws, open to all experience levels.', instagram: 'ntuaikidoclub' },
  { name: 'Brazilian Jiu-Jitsu', type: 'Sports', desc: 'Ground grappling and submission wrestling, open to complete beginners through to competitors.', instagram: 'ntu.jiujitsu' },
  { name: 'Judo Club', type: 'Sports', desc: 'Olympic-style judo training with grading opportunities and IVP competitive representation.', instagram: 'ntujudo' },
  { name: 'Muay Thai Club', type: 'Sports', desc: 'Thai boxing training covering strikes, clinch work and pad work for fitness and competition.', instagram: 'ntumuaythai' },
  { name: 'Shitoryu Karate-Do', type: 'Sports', desc: 'Traditional Shitoryu-style karate with kata and kumite training, IVP competition participation.', instagram: 'ntukarate' },
  { name: 'Silat', type: 'Sports', desc: 'Malay martial art Pencak Silat, blending self-defence, performance and cultural heritage.', instagram: 'ntusilat' },
  { name: 'Taekwondo', type: 'Sports', desc: 'Olympic taekwondo with poomsae and sparring training, belt gradings and varsity competition.', instagram: 'ntutkd' },
  { name: 'Wushu', type: 'Sports', desc: 'Chinese martial art combining form and sparring disciplines, representing NTU at varsity level.', instagram: 'ntucacwushu' },
  { name: "Women's Contact Rugby", type: 'Sports', desc: "NTU's women's contact rugby team competing at varsity and inter-university level.", instagram: 'ntuwomensrugby' },
  { name: 'Track and Field', type: 'Sports', desc: 'Athletics club covering sprints, middle distance, field events and cross-country with IVP representation.', instagram: 'ntu.athletics' },
  { name: 'Canoe Kayak Sprint', type: 'Sports', desc: 'Flatwater sprint kayaking at varsity level, training at Bedok Reservoir with IVP competition.', instagram: 'ntucanoesprint' },
  { name: 'Dragon Boat', type: 'Sports', desc: 'Dragon boat paddling team competing at local and regional regattas throughout the year.', instagram: 'ntudragonboat' },
  { name: 'Calisthenics Club', type: 'Sports', desc: 'Bodyweight strength and skills training — muscle-ups, handstands, levers and freestyle movement.', instagram: 'ntu_calisthenics' },
  { name: 'Squash Club', type: 'Sports', desc: 'Competitive and recreational squash with varsity representation in IVP leagues and local tournaments.', instagram: 'ntusquashers' },
  { name: 'Aquathlon Club', type: 'Sports', desc: 'Combined swim-and-run multisport, training for aquathlon races and triathlon events around Singapore.', instagram: 'ntuaquathlon' },
  { name: "Men's Touch Football", type: 'Sports', desc: 'Non-contact touch football with regular training sessions and inter-varsity competition.', instagram: 'ntu_menstouchfootball' },

  /* ── Arts — Music ── */
  { name: 'Choir', type: 'Arts', desc: "NTU's premier choral ensemble, performing Western classical and Asian repertoire locally and internationally.", instagram: 'ntuchoir' },
  { name: 'Chinese Orchestra (NTUCO)', type: 'Arts', desc: 'Full Chinese orchestra performing traditional and contemporary Chinese orchestral repertoire on concert stages.', instagram: 'ntu.chineseorchestra' },
  { name: 'Symphonic Band (NTUSB)', type: 'Arts', desc: 'Full concert band under Resident Conductor Takehiro Oura, competing internationally and staging annual Sojourn concerts.', instagram: 'ntusb' },
  { name: 'Symphony Orchestra (NTUSO)', type: 'Arts', desc: 'Western symphony orchestra giving full orchestral concerts each semester on and off campus.', instagram: 'ntusymphonyorchestra' },
  { name: 'Guitar Ensemble', type: 'Arts', desc: 'Classical and Niibori-system guitar orchestra, one of Singapore\'s first, with public performances and masterclasses.', instagram: 'ntuguitarensemble' },
  { name: 'Chinese Drums', type: 'Arts', desc: 'Chinese percussion ensemble performing traditional and fusion pieces at cultural events and competitions.', instagram: 'ntu_chinesedrums' },
  { name: 'Harmonica Band', type: 'Arts', desc: 'Ensemble performing classical and pop pieces on chromatic and diatonic harmonicas.', instagram: 'ntuhb' },
  { name: 'Harmonix (A Cappella)', type: 'Arts', desc: "NTU's a cappella group blending contemporary pop, jazz and original arrangements without instruments.", instagram: 'ntuharmonix' },
  { name: 'Jazz & Blues Society', type: 'Arts', desc: 'Jazz and blues jams, workshops and concerts bringing live improvised music to the NTU campus.', instagram: 'ntujazzandblues' },
  { name: 'Piano Ensemble', type: 'Arts', desc: 'Solo, duo and ensemble piano performances across classical, pop and contemporary genres.', instagram: 'ntupianoensemble' },

  /* ── Arts — Dance ── */
  { name: 'Breakers', type: 'Arts', desc: 'B-boy/b-girl breakdancing crew competing at local and regional battles and events.', instagram: 'ntubreakers' },
  { name: 'Chinese Dance Club', type: 'Arts', desc: 'Classical and folk Chinese dance, representing NTU at competitions and cultural performances.', instagram: 'ntu.chinesedance' },
  { name: 'Contemp{minated}', type: 'Arts', desc: 'Contemporary dance collective pushing creative boundaries through experimental choreography and production.', instagram: 'contempminated' },
  { name: 'DanceSport Academy', type: 'Arts', desc: 'Ballroom and Latin competitive dance, training couples for university and national dancesport competitions.', instagram: 'ntu_dsa' },
  { name: 'Indian Dance Club (NTUID)', type: 'Arts', desc: 'NTU\'s first Indian dance club, showcasing Bharatanatyam and contemporary Indian dance forms since 2019.', instagram: 'ntuindiandance' },
  { name: 'Lindy Hop', type: 'Arts', desc: 'Swing dance community teaching Lindy Hop, Charleston and Blues in a social dance setting.', instagram: 'ntulindyhop' },
  { name: 'MJ (Hip Hop)', type: 'Arts', desc: 'Street dance club covering hip hop, popping, locking and new-style, with showcases and battles.', instagram: 'ntumj' },
  { name: 'Soul Funky Pop & Lock', type: 'Arts', desc: 'Popping and locking dance crew performing at campus events and local competitions.', instagram: 'ntusoulfunky' },
  { name: 'Dragon & Lion Dance Troupe', type: 'Arts', desc: 'Traditional Chinese dragon and lion dance performances at Chinese New Year and cultural events.', instagram: 'ntu_liondance' },
  { name: 'Salsa En Sync', type: 'Arts', desc: 'Latin social dance community teaching salsa, bachata and other Latin styles through weekly socials.', instagram: 'ntusalsa' },

  /* ── Arts — Performing & Visual ── */
  { name: 'Epiphany (NTU English Drama Society)', type: 'Arts', desc: 'English-language theatre productions, comedy improv, workshops and the annual Main Stage show.', instagram: 'ntudrama' },
  { name: 'Nanyang Arts Ensemble (NAE)', type: 'Arts', desc: 'Visual arts and crafts community running biweekly workshops — crochet, beadwork, painting and more.', instagram: 'ntu_nae' },
  { name: 'Film Society', type: 'Arts', desc: 'Film screenings, discussions and short film productions for cinephiles and aspiring filmmakers.', instagram: 'ntufilm' },
  { name: 'Photo-Videographic Society (NTUPVS)', type: 'Arts', desc: 'Photography and videography community across digital, film and video disciplines, founded in 1984.', instagram: 'ntupvs' },
  { name: 'Visual Arts Society (VAS)', type: 'Arts', desc: 'Painting, drawing, illustration and mixed-media art, running workshops and exhibitions on campus.', instagram: 'ntuvas' },
  { name: 'Emcee Club', type: 'Arts', desc: 'Develops student MCs for NTU events — public speaking, stage presence and event hosting skills.', instagram: 'ntuemcees' },
  { name: 'Concert Engineers', type: 'Arts', desc: 'Live sound, lighting and production crew behind NTU\'s major CAC concerts and performances.', instagram: 'ntuconcerteng' },
  { name: 'Miniaturists and Modellers Club', type: 'Arts', desc: 'Scale modelling, miniatures, dioramas and tabletop hobby crafts — painting workshops, building sessions and community showcases.', instagram: 'minisatntu' },
  { name: 'Fashion and Makeup Club', type: 'Arts', desc: 'Creative community exploring fashion styling, makeup artistry and visual presentation through workshops and showcases.', instagram: 'ntu.fam' },
  { name: 'CAC Media and Infotech', type: 'Arts', desc: 'CAC media arm handling digital content, visual production and broadcast support for NTU cultural events.', instagram: 'ntucac_mit' },

  /* ── Cultural ── */
  { name: 'Chinese Society', type: 'Cultural', desc: 'Celebrates Chinese language, arts and festivals through cultural camps, performances and community events.', instagram: 'ntuchinesesoc' },
  { name: 'Tamil Literary Society (TLS)', type: 'Cultural', desc: 'Promotes Tamil language and South Indian culture through literature events, Deepavali celebrations and community programmes.', instagram: 'ntutls' },
  { name: 'Malay Language and Cultural Society (PERBAYU)', type: 'Cultural', desc: 'Preserves Malay language and culture through performances, cultural fests and language activities since 1991.', instagram: 'ntuperbayu' },
  { name: 'Korean Cultural Society', type: 'Cultural', desc: 'K-pop, K-drama, Korean language and food events for fans and learners of Korean culture.', instagram: 'ntukdp' },
  { name: 'Japanese Appreciation Club (JAC)', type: 'Cultural', desc: 'Japanese language, anime, food and cultural exchange between NTU students and Japanese exchange students.', instagram: 'ntujac' },
  { name: 'Indian Society (IndSoc)', type: 'Cultural', desc: 'A community celebrating Indian culture and heritage through Holi, Diwali and cultural exchange events.', instagram: 'indsoc_ntu' },
  { name: 'Heritage Club', type: 'Cultural', desc: 'Raises awareness of Singapore\'s cultural heritage through tours, talks and the annual Heritage Week.', instagram: 'ntu_heritage_club' },
  { name: 'NTU Christian Fellowship', type: 'Cultural', desc: 'Pan-denominational Christian community with Bible study, prayer groups and cell groups in English, Chinese and Indonesian.', instagram: 'ntucf' },
  { name: 'NTU Cru', type: 'Cultural', desc: 'Campus ministry running Bible discussions, leadership training and outreach events for students of all backgrounds.', instagram: 'ntucru' },
  { name: 'NTU Muslim Society', type: 'Cultural', desc: 'Muslim student community hosting Ramadan iftars, Islamic talks, welfare drives and interfaith dialogue events.', instagram: 'myntums' },
  { name: 'NTU Buddhist Society', type: 'Cultural', desc: 'Buddhist community offering meditation sessions, Dharma talks, retreats and cultural activities for members.', instagram: 'ntubuddhist' },
  { name: 'NTU Tabernacle Fellowship', type: 'Cultural', desc: 'Christian fellowship community centred on worship, discipleship and campus outreach for NTU students.', instagram: 'ntutf' },

  /* ── Academic ── */
  { name: 'IEEE NTU Student Branch', type: 'Academic', desc: 'IEEE student chapter running iNTUition hackathon, technical workshops and industry networking events.', instagram: 'ieee_ntu' },
  { name: 'NTU Entrepreneurship Society', type: 'Academic', desc: 'NTU\'s premier student entrepreneurship body — startup pitches, incubation support and founder networking since 2000.', instagram: 'ntu_es' },
  { name: 'Investment Interactive Club (IIC)', type: 'Academic', desc: 'Stock pitch competitions, investment simulations and finance industry networking for aspiring investors.', instagram: 'ntu.iic' },
  { name: 'NTU Open Source Society (NTUOSS)', type: 'Academic', desc: 'Hacker club fostering open-source development through workshops, project nights and the Git community since 1998.', instagram: 'ntuoss' },
  { name: 'AIESEC NTU', type: 'Academic', desc: 'Global youth leadership organisation offering international internships, exchanges and leadership development.', instagram: 'aiesec_ntu' },
  { name: 'Debating Society', type: 'Academic', desc: 'Competitive parliamentary debating, public speaking workshops and Model UN preparation.', instagram: 'ntudebatesoc' },
  { name: 'Toastmasters Club', type: 'Academic', desc: 'Public speaking and leadership development through structured speeches, table topics and peer evaluations.', instagram: 'ntu.toastmastersclub' },
  { name: 'Management Consulting Club', type: 'Academic', desc: 'Case competitions, consulting workshops and industry networking for students interested in management consulting.', instagram: 'ntumcclub' },
  { name: 'Nanyang Capital', type: 'Academic', desc: 'Student-run investment fund combining finance education with real portfolio management experience.', instagram: 'nanyangcapitalsg' },
  { name: 'NTU Esports Society', type: 'Academic', desc: 'Competitive and recreational gaming across popular titles, with tournaments and inter-varsity representation.', instagram: 'ntu_esports' },
  { name: 'Women in Tech NTU', type: 'Academic', desc: 'Community empowering women in STEM through mentorship, networking and industry speaker events.', instagram: 'ntu_witech' },
  { name: 'NTU SCDS Club', type: 'Academic', desc: "Students' Computing and Data Science Club — organises Techfest hackathons, career events and community activities for CCDS students.", instagram: 'ntuscdsclub' },
  { name: 'NTU SCSE Club', type: 'Academic', desc: 'Computer Science and Engineering student club running coding competitions, industry talks and networking for SCSE students.', instagram: 'ntucseclub' },
  { name: 'NTU AIML Club', type: 'Academic', desc: 'AI/ML community under SCDS running workshops, competitions and the CACTUS team for students passionate about artificial intelligence.', instagram: 'ccds_aiml' },
  { name: '180 Degrees Consulting (Nanyang)', type: 'Academic', desc: 'Global non-profit consulting club connecting NTU students with real consulting projects for social enterprises and NGOs.', instagram: '180dcntu' },
  { name: 'NTU Business Solutions', type: 'Academic', desc: 'Business case club offering case competition training, consulting workshops and career development for business-minded students.', instagram: 'ntubusinesssolutions' },
  { name: 'NTU Astronomical Society', type: 'Academic', desc: 'Stargazing sessions, astrophotography, telescope workshops and space science talks for the curious.', instagram: 'ntu_astro' },
  { name: 'UAVionics Society', type: 'Academic', desc: 'Drone engineering and UAV development club building, flying and competing with unmanned aerial systems.', instagram: 'ntu_uavionics_society' },
  { name: 'NTU Biomedical Engineering Society (BMES)', type: 'Academic', desc: 'Community for BME students and enthusiasts — industry talks, research exposure and career development.', instagram: 'ntubmes' },
  { name: 'NTU Corporate Banking Club', type: 'Academic', desc: 'Finance club focused on corporate and investment banking — case workshops, deal simulations and industry networking.', instagram: 'ntu.corporatebankingclub' },
  { name: 'NTU Cybersecurity Club (root@NTU)', type: 'Academic', desc: 'CTF competitions, security workshops and hands-on hacking labs for students passionate about cybersecurity.', instagram: 'ntucybersec' },
  { name: 'Blockchain @ NTU', type: 'Academic', desc: 'Blockchain and Web3 community running developer workshops, hackathons and industry talks on decentralised technologies.', instagram: 'blockchain.ntusg' },

  /* ── Community ── */
  { name: 'Earthlink NTU', type: 'Community', desc: 'NTU\'s largest environmental sustainability club — tree planting, eco-campaigns and community nature events.', instagram: 'earthlinkntu' },
  { name: 'Rotaract Club of NTU', type: 'Community', desc: 'Rotary-affiliated service club running community outreach, social projects and leadership development programmes.', instagram: 'racntu' },
  { name: 'Welfare Services Club (WSC)', type: 'Community', desc: 'Constituent club running 9 service projects for the deaf, elderly, disabled and other vulnerable communities.', instagram: 'ntuwsc' },
  { name: 'Uni-Y NTU', type: 'Community', desc: 'University YMCA chapter running youth development, community service and leadership programmes.', instagram: 'uniysg' },
  { name: 'Engineers Without Borders NTU', type: 'Community', desc: 'Applies engineering skills to humanitarian projects in Singapore and developing communities overseas.', instagram: 'ewb.ntu' },
  { name: 'NTU Civil Defence Lionhearter Club', type: 'Community', desc: 'Civil defence awareness and community preparedness — partnered with SCDF to train student volunteers.', instagram: 'ntulionhearters' },
  { name: 'Fastforward Board Games Society', type: 'Community', desc: 'Casual and competitive board gaming — game nights, tournaments and a growing library of tabletop titles.', instagram: 'ntu_fastforward' },
  { name: 'NTU Wine Society', type: 'Community', desc: 'Wine appreciation society running tastings, pairing sessions and vineyard visits for curious palates.', instagram: 'ntuwinesociety' },

  /* ── Uniformed ── */
  { name: 'Red Cross Youth NTU Chapter', type: 'Uniformed', desc: 'Bi-annual blood donation drives, first aid coverage and community involvement programmes since 1994.', instagram: 'nturedcross' },
  { name: 'National Police Cadet Corps (NPCC)', type: 'Uniformed', desc: 'One of two open NPCC university units — crime prevention, police liaison and leadership training.', instagram: 'ntunpcc' },

  /* ── Welfare ── */
  { name: "Students' Union (NTUSU)", type: 'Welfare', desc: "Representative body of all NTU undergraduates — student advocacy, campus-wide events and club governance.", instagram: 'ntu.su' },
  { name: "Animal Lovers' Society (ALS)", type: 'Welfare', desc: 'Animal welfare advocacy, adoption drives and volunteering with local shelters and community cat programmes.', instagram: 'ntuals' },
];
